# debug flag this runs pipeline with only 10 files
DEBUG: False

# AIA resolution to use
RESOLUTION: 256

# Whether to remove off limb or on not
REMOVE_OFFLIMB: False

# Value for the offlimb
VALUE_OFFLIMB: 0

# AIA location
aia_path: "/mnt/miniset/aia-jsoc"

# AIA preprocesed stack
aia_stack_path: "/mnt/miniset/aia-stacks"

# Location of FDL 2018 eve data
eve_base_path: "/home/miraflorista/sw-irradiance/data/EVE"

# Path to place all calculations
sw-irr-matches_path: "/home/andres_munoz_j/eve-matches"

# Path to place all calculations
sw-irr-output_path: "/home/andres_munoz_j/sw-irr-output"

# NN config path
nn_config_path: "/home/andres_munoz_j/sw-irradiance/config_residuals"

# NN config file name (no extension)
nn_config_file: "anet_3_bn_15"

# Wildcards
EVE-NORM-STATISTIC: ["mean","std"]
AIA-NORM-STATISTIC: ["mean","sqrt_mean","std","sqrt_std"]
SPLIT: ["train","test","val"]
TRAIN_OUTPUTS: ["log.txt", "model.pt"]
PHASE: ["test"]
