# debug flag this runs pipeline with only 10 files
DEBUG: False

# AIA resolution to use
RESOLUTION: 256

# Whether to remove off limb or on not
REMOVE_OFFLIMB: False

# Value for the offlimb
VALUE_OFFLIMB: 0

# AIA location
aia_path: "/mnt/miniset/aia-jsoc"

# AIA preprocesed stack
aia_stack_path: "/mnt/miniset/aia-stacks"

# Location of FDL 2018 eve data
eve_base_path: "/home/miraflorista/sw-irradiance/data/EVE"

# Path to place all calculations
sw-irr-output_path: "/home/andres_munoz_j/sw-irr-output"

# Model results
model_results_path: "home/andres_munoz_j/model_results"

# Wildcards
EVE-NORM-STATISTIC: ["mean","std"]
AIA-NORM-STATISTIC: ["mean","sqrt_mean","std","sqrt_std"]
SPLIT: ["train","test","val"]
phase: ["test"]
