
# AIA location
aia_path: "/mnt/miniset/aia-jsoc"

# Location of FDL 2018 eve data
eve_base_path: "/home/miraflorista/sw-irradiance/data/EVE"

# Path to place all calculations
sw-irr-output_path: "/home/andres_munoz_j/sw-irr-output"

# Model results
model_results_path: "home/andres_munoz_j/model_results"

# Wildcards
EVE-NORM-STATISTIC: ["mean","std"]
AIA-NORM-STATISTIC: ["mean","sqrt_mean","std","sqrt_std"]
SPLIT: ["train","test","val"]
phase: ["test"]
